FROM golang:1.11.1-alpine as build

RUN apk add --no-cache gcc musl-dev taglib-dev git

RUN mkdir /src

COPY ./mp3db /src
WORKDIR /src

RUN go build -o mp3db main.go

# ----------------

FROM alpine:3.7

RUN apk add --no-cache ca-certificates taglib

RUN mkdir /app

COPY --from=build /src/mp3db /app

ADD mp3db-config.yml /app/

ENV ENV production

EXPOSE 8082

WORKDIR /app

CMD [ "./mp3db", "serve" ]

