FROM golang:1.13.5-alpine as build

RUN apk add --no-cache gcc musl-dev taglib-dev ca-certificates git

RUN mkdir /src

WORKDIR /src

# Copy only go.mod and go.sum and than download the dependencies so that they will be cached
COPY ./mp3db/go.mod ./mp3db/go.sum ./
RUN go mod download

COPY ./mp3db .

RUN go build -o mp3db main.go

# ----------------

FROM alpine:3.7

RUN apk add --no-cache ca-certificates taglib

RUN mkdir /app

COPY --from=build /src/mp3db /app

ADD mp3db-config.yml /app/

ENV ENV production

EXPOSE 8082

WORKDIR /app

CMD [ "./mp3db", "serve" ]

