version: '3'
services:
  caddy:
    build:
      context: ./
      dockerfile: Dockerfile-caddy
    restart: always
    links:
      - mp3db
    ports:
      - 8081:8081
    volumes:
      - "${PWD}/log:/var/log"
      - "${PWD}/certificates:/app/certificates"
      - "${PWD}/Caddyfile:/etc/Caddyfile"

  mp3db:
    build:
      context: ./
      dockerfile: Dockerfile-mp3db
    restart: always
    ports:
      - 8082:8082
    volumes:
      - "${PWD}/data:/data"
      - "/volume1/music:/music"
